# Directors

## Imports

In [1]:
!pip install \
pandas \
sqlalchemy \
plotly \
huggingface_hub \
dotenv \
tqdm \
opencv-python \
scipy \
duckdb-sqlalchemy \
statsmodels \
kaleido \
nbformat

Requirement already satisfied: pandas in /home/amos/anaconda3/envs/stat/lib/python3.11/site-packages (2.3.0)
Requirement already satisfied: sqlalchemy in /home/amos/anaconda3/envs/stat/lib/python3.11/site-packages (2.0.41)
Requirement already satisfied: plotly in /home/amos/anaconda3/envs/stat/lib/python3.11/site-packages (6.2.0)
Collecting huggingface_hub
  Downloading huggingface_hub-1.21.0-py3-none-any.whl.metadata (14 kB)
Collecting dotenv
  Using cached dotenv-0.9.9-py2.py3-none-any.whl.metadata (279 bytes)
Collecting tqdm
  Downloading tqdm-4.68.3-py3-none-any.whl.metadata (57 kB)
Collecting opencv-python
  Downloading opencv_python-4.13.0.92-cp37-abi3-manylinux_2_28_x86_64.whl.metadata (19 kB)
Collecting scipy
  Using cached scipy-1.17.1-cp311-cp311-manylinux_2_27_x86_64.manylinux_2_28_x86_64.whl.metadata (62 kB)
Collecting duckdb-sqlalchemy
  Using cached duckdb_sqlalchemy-1.5.3-py3-none-any.whl.metadata (10 kB)
Collecting statsmodels
  Using cached statsmodels-0.14.6-cp311-cp311-manylinux2014_x86_64.manylinux_2_17_x86_64.manylinux_2_28_x86_64.whl.metadata (9.5 kB)
Collecting kaleido
  Downloading kaleido-1.3.0-py3-none-any.whl.metadata (5.6 kB)
Requirement already satisfied: nbformat in /home/amos/anaconda3/envs/stat/lib/python3.11/site-packages (5.10.4)
Requirement already satisfied: numpy>=1.23.2 in /home/amos/anaconda3/envs/stat/lib/python3.11/site-packages (from pandas) (2.3.1)
Requirement already satisfied: python-dateutil>=2.8.2 in /home/amos/anaconda3/envs/stat/lib/python3.11/site-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in /home/amos/anaconda3/envs/stat/lib/python3.11/site-packages (from pandas) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in /home/amos/anaconda3/envs/stat/lib/python3.11/site-packages (from pandas) (2025.2)
Requirement already satisfied: greenlet>=1 in /home/amos/anaconda3/envs/stat/lib/python3.11/site-packages (from sqlalchemy) (3.2.3)
Requirement already satisfied: typing-extensions>=4.6.0 in /home/amos/anaconda3/envs/stat/lib/python3.11/site-packages (from sqlalchemy) (4.14.0)
Requirement already satisfied: narwhals>=1.15.1 in /home/amos/anaconda3/envs/stat/lib/python3.11/site-packages (from plotly) (1.44.0)
Requirement already satisfied: packaging in /home/amos/anaconda3/envs/stat/lib/python3.11/site-packages (from plotly) (25.0)
Collecting click>=8.4.0 (from huggingface_hub)
  Downloading click-8.4.2-py3-none-any.whl.metadata (2.6 kB)
Collecting filelock>=3.10.0 (from huggingface_hub)
  Downloading filelock-3.29.4-py3-none-any.whl.metadata (2.0 kB)
Collecting fsspec>=2023.5.0 (from huggingface_hub)
  Downloading fsspec-2026.6.0-py3-none-any.whl.metadata (10 kB)
Collecting hf-xet<2.0.0,>=1.5.1 (from huggingface_hub)
  Downloading hf_xet-1.5.1-cp37-abi3-manylinux2014_x86_64.manylinux_2_17_x86_64.whl.metadata (4.9 kB)
Collecting httpx<1,>=0.23.0 (from huggingface_hub)
  Using cached httpx-0.28.1-py3-none-any.whl.metadata (7.1 kB)
Requirement already satisfied: pyyaml>=5.1 in /home/amos/anaconda3/envs/stat/lib/python3.11/site-packages (from huggingface_hub) (6.0.3)
Collecting typer<0.26.0,>=0.20.0 (from huggingface_hub)
  Downloading typer-0.25.1-py3-none-any.whl.metadata (15 kB)
Requirement already satisfied: anyio in /home/amos/anaconda3/envs/stat/lib/python3.11/site-packages (from httpx<1,>=0.23.0->huggingface_hub) (4.14.1)
Requirement already satisfied: certifi in /home/amos/anaconda3/envs/stat/lib/python3.11/site-packages (from httpx<1,>=0.23.0->huggingface_hub) (2025.6.15)
Collecting httpcore==1.* (from httpx<1,>=0.23.0->huggingface_hub)
  Using cached httpcore-1.0.9-py3-none-any.whl.metadata (21 kB)
Requirement already satisfied: idna in /home/amos/anaconda3/envs/stat/lib/python3.11/site-packages (from httpx<1,>=0.23.0->huggingface_hub) (3.10)
Requirement already satisfied: h11>=0.16 in /home/amos/anaconda3/envs/stat/lib/python3.11/site-packages (from httpcore==1.*->httpx<1,>=0.23.0->huggingface_hub) (0.16.0)
Collecting shellingham>=1.3.0 (from typer<0.26.0,>=0.20.0->huggingface_hub)
  Using cached shellingham-1.5.4-py2.py3-none-any.whl.metadata (3.5 kB)
Collecting rich>=13.8.0 (from typer<0.26.0,>=0.20.0->huggingface_hub)
  Downloading rich-15.0.0-py3-none-any.whl.metadata (18 kB)
Collecting annotated-doc>=0.0.2 (from typer<0.26.0,>=0.20.0->huggingface_hub)
  Using cached annotated_doc-0.0.4-py3-none-any.whl.metadata (6.6 kB)
Requirement already satisfied: python-dotenv in /home/amos/anaconda3/envs/stat/lib/python3.11/site-packages (from dotenv) (1.1.1)
Collecting duckdb>=0.5.0 (from duckdb-sqlalchemy)
  Downloading duckdb-1.5.4-cp311-cp311-manylinux_2_26_x86_64.manylinux_2_28_x86_64.whl.metadata (4.2 kB)
Collecting sqlalchemy
  Using cached sqlalchemy-2.0.51-cp311-cp311-manylinux2014_x86_64.manylinux_2_17_x86_64.manylinux_2_28_x86_64.whl.metadata (9.5 kB)
Collecting patsy>=0.5.6 (from statsmodels)
  Using cached patsy-1.0.2-py2.py3-none-any.whl.metadata (3.6 kB)
Collecting choreographer>=1.3.0 (from kaleido)
  Downloading choreographer-1.3.0-py3-none-any.whl.metadata (6.9 kB)
Collecting logistro>=1.0.8 (from kaleido)
  Using cached logistro-2.0.1-py3-none-any.whl.metadata (3.9 kB)
Collecting orjson>=3.10.15 (from kaleido)
  Downloading orjson-3.11.9-cp311-cp311-manylinux_2_17_x86_64.manylinux2014_x86_64.whl.metadata (41 kB)
Requirement already satisfied: fastjsonschema>=2.15 in /home/amos/anaconda3/envs/stat/lib/python3.11/site-packages (from nbformat) (2.21.1)
Requirement already satisfied: jsonschema>=2.6 in /home/amos/anaconda3/envs/stat/lib/python3.11/site-packages (from nbformat) (4.24.0)
Requirement already satisfied: jupyter-core!=5.0.*,>=4.12 in /home/amos/anaconda3/envs/stat/lib/python3.11/site-packages (from nbformat) (5.8.1)
Requirement already satisfied: traitlets>=5.1 in /home/amos/anaconda3/envs/stat/lib/python3.11/site-packages (from nbformat) (5.14.3)
Requirement already satisfied: platformdirs>=4.3.6 in /home/amos/anaconda3/envs/stat/lib/python3.11/site-packages (from choreographer>=1.3.0->kaleido) (4.3.8)
Collecting simplejson>=3.19.3 (from choreographer>=1.3.0->kaleido)
  Downloading simplejson-4.1.1-cp311-cp311-manylinux1_x86_64.manylinux_2_28_x86_64.manylinux_2_5_x86_64.whl.metadata (3.8 kB)
Requirement already satisfied: attrs>=22.2.0 in /home/amos/anaconda3/envs/stat/lib/python3.11/site-packages (from jsonschema>=2.6->nbformat) (25.3.0)
Requirement already satisfied: jsonschema-specifications>=2023.03.6 in /home/amos/anaconda3/envs/stat/lib/python3.11/site-packages (from jsonschema>=2.6->nbformat) (2025.4.1)
Requirement already satisfied: referencing>=0.28.4 in /home/amos/anaconda3/envs/stat/lib/python3.11/site-packages (from jsonschema>=2.6->nbformat) (0.36.2)
Requirement already satisfied: rpds-py>=0.7.1 in /home/amos/anaconda3/envs/stat/lib/python3.11/site-packages (from jsonschema>=2.6->nbformat) (0.25.1)
Requirement already satisfied: six>=1.5 in /home/amos/anaconda3/envs/stat/lib/python3.11/site-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)
Collecting markdown-it-py>=2.2.0 (from rich>=13.8.0->typer<0.26.0,>=0.20.0->huggingface_hub)
  Downloading markdown_it_py-4.2.0-py3-none-any.whl.metadata (7.4 kB)
Requirement already satisfied: pygments<3.0.0,>=2.13.0 in /home/amos/anaconda3/envs/stat/lib/python3.11/site-packages (from rich>=13.8.0->typer<0.26.0,>=0.20.0->huggingface_hub) (2.19.2)
Collecting mdurl~=0.1 (from markdown-it-py>=2.2.0->rich>=13.8.0->typer<0.26.0,>=0.20.0->huggingface_hub)
  Using cached mdurl-0.1.2-py3-none-any.whl.metadata (1.6 kB)
Downloading huggingface_hub-1.21.0-py3-none-any.whl (721 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 721.1/721.1 kB 12.4 MB/s eta 0:00:00
Downloading hf_xet-1.5.1-cp37-abi3-manylinux2014_x86_64.manylinux_2_17_x86_64.whl (4.5 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 4.5/4.5 MB 60.5 MB/s eta 0:00:00
Using cached httpx-0.28.1-py3-none-any.whl (73 kB)
Using cached httpcore-1.0.9-py3-none-any.whl (78 kB)
Downloading typer-0.25.1-py3-none-any.whl (58 kB)
Using cached dotenv-0.9.9-py2.py3-none-any.whl (1.9 kB)
Downloading tqdm-4.68.3-py3-none-any.whl (78 kB)
Downloading opencv_python-4.13.0.92-cp37-abi3-manylinux_2_28_x86_64.whl (72.9 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 72.9/72.9 MB 79.7 MB/s eta 0:00:00a 0:00:01
Using cached scipy-1.17.1-cp311-cp311-manylinux_2_27_x86_64.manylinux_2_28_x86_64.whl (35.3 MB)
Using cached duckdb_sqlalchemy-1.5.3-py3-none-any.whl (66 kB)
Using cached sqlalchemy-2.0.51-cp311-cp311-manylinux2014_x86_64.manylinux_2_17_x86_64.manylinux_2_28_x86_64.whl (3.3 MB)
Using cached statsmodels-0.14.6-cp311-cp311-manylinux2014_x86_64.manylinux_2_17_x86_64.manylinux_2_28_x86_64.whl (10.4 MB)
Downloading kaleido-1.3.0-py3-none-any.whl (55 kB)
Using cached annotated_doc-0.0.4-py3-none-any.whl (5.3 kB)
Downloading choreographer-1.3.0-py3-none-any.whl (52 kB)
Downloading click-8.4.2-py3-none-any.whl (119 kB)
Downloading duckdb-1.5.4-cp311-cp311-manylinux_2_26_x86_64.manylinux_2_28_x86_64.whl (21.5 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 21.5/21.5 MB 72.2 MB/s eta 0:00:00a 0:00:01
Downloading filelock-3.29.4-py3-none-any.whl (42 kB)
Downloading fsspec-2026.6.0-py3-none-any.whl (203 kB)
Using cached logistro-2.0.1-py3-none-any.whl (8.6 kB)
Downloading orjson-3.11.9-cp311-cp311-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (133 kB)
Using cached patsy-1.0.2-py2.py3-none-any.whl (233 kB)
Downloading rich-15.0.0-py3-none-any.whl (310 kB)
Downloading markdown_it_py-4.2.0-py3-none-any.whl (91 kB)
Using cached mdurl-0.1.2-py3-none-any.whl (10.0 kB)
Using cached shellingham-1.5.4-py2.py3-none-any.whl (9.8 kB)
Downloading simplejson-4.1.1-cp311-cp311-manylinux1_x86_64.manylinux_2_28_x86_64.manylinux_2_5_x86_64.whl (180 kB)
Installing collected packages: tqdm, sqlalchemy, simplejson, shellingham, scipy, patsy, orjson, opencv-python, mdurl, logistro, httpcore, hf-xet, fsspec, filelock, duckdb, dotenv, click, annotated-doc, markdown-it-py, httpx, duckdb-sqlalchemy, choreographer, statsmodels, rich, kaleido, typer, huggingface_hub
  Attempting uninstall: sqlalchemy
    Found existing installation: SQLAlchemy 2.0.41
    Uninstalling SQLAlchemy-2.0.41:
      Successfully uninstalled SQLAlchemy-2.0.41
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 27/27 [huggingface_hub] [huggingface_hub]y]
Successfully installed annotated-doc-0.0.4 choreographer-1.3.0 click-8.4.2 dotenv-0.9.9 duckdb-1.5.4 duckdb-sqlalchemy-1.5.3 filelock-3.29.4 fsspec-2026.6.0 hf-xet-1.5.1 httpcore-1.0.9 httpx-0.28.1 huggingface_hub-1.21.0 kaleido-1.3.0 logistro-2.0.1 markdown-it-py-4.2.0 mdurl-0.1.2 opencv-python-4.13.0.92 orjson-3.11.9 patsy-1.0.2 rich-15.0.0 scipy-1.17.1 shellingham-1.5.4 simplejson-4.1.1 sqlalchemy-2.0.51 statsmodels-0.14.6 tqdm-4.68.3 typer-0.25.1

In [2]:
import sys
from pathlib import Path 

import pandas as pd
import sqlalchemy as db
import plotly.express as px
from huggingface_hub import hf_hub_download
from tqdm.auto import tqdm 
from dotenv import find_dotenv, load_dotenv

/home/amos/anaconda3/envs/stat/lib/python3.11/site-packages/tqdm/auto.py:21: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm

In [3]:
import plotly.io as pio
pio.renderers.default = "notebook_connected"

## Setup

In [4]:
# 1. Load variables (makes 'import utils' work via PYTHONPATH=.)
load_dotenv(find_dotenv())

# 2. Define the project root based on where the .env file lives
ROOT_DIR = Path(find_dotenv()).parent

# 3. Explicitly anchor the notebook folder to the root 
# (Change this string depending on which subfolder the notebook lives in)
NOTEBOOK_DIR = ROOT_DIR / "research" / "baselines"

In [5]:
if str(ROOT_DIR) not in sys.path:
    sys.path.append(str(ROOT_DIR))

from utils import *

In [6]:
layout = {
    'title': {
        'text': '',
        'font': {'size': 22, 'family': 'Raleway', 'color': 'white'},
        'x': 0.5,
        'y': 0.95,
        'xanchor': 'center',
        'yanchor': 'top'
    },
    'xaxis': {
        'title': {
            'text': '',
            'font': {'size': 18, 'family': 'Raleway', 'color': 'white'} 
        },
        'tickfont': {'size': 14, 'family': 'Roboto', 'color': 'white'}
    },
    'yaxis': {
        'layer': 'below traces',
        'title': {
            'text': '',
            'font': {'size': 18, 'family': 'Raleway', 'color': 'white'} 
        },
        'tickfont': {'size': 14, 'family': 'Roboto', 'color': 'white'}
    },
    'font': {'color': 'white'},
    'paper_bgcolor': '#1A1A2E',
    'plot_bgcolor': 'rgba(61, 61, 61, 0)'
}

In [7]:
Path("./plots").mkdir(exist_ok=True)

## Load Data

In [8]:
dw_local_path = hf_hub_download(
    repo_id="astaileyyoung/CineStat",
    filename="CineStat_agg.duckdb",
    repo_type="dataset",
    local_dir=str(ROOT_DIR)
)

In [9]:
db_url = f"duckdb:///{ROOT_DIR / 'CineStat_agg.duckdb'}"
engine = db.create_engine(db_url, connect_args={"read_only": True})

In [10]:
df = pd.read_sql("SELECT * FROM vwWorksByDirector WHERE kind = 'movie'", engine)
df

,person_id,person_name,title,year,kind,runtime,fact_id,imdb_id,work_id,avg_size,...,z_v_density_tv,z_v_density_tv_g,z_pct_face_tv,z_pct_face_tv_g,z_v_pct_face_tv,z_v_pct_face_tv_g,z_pct_top1_tv,z_pct_top1_tv_g,z_v_pct_top1_tv,z_v_pct_top1_tv_g
0,100036,D.W. Griffith,The Avenging Conscience: or 'Thou Shalt Not Kill',1914,movie,78.0,251,3643,32807,0.0176,...,None,None,None,None,None,None,None,None,None,None
1,41611,Giovanni Pastrone,Cabiria,1914,movie,148.0,256,3740,32809,0.0056,...,None,None,None,None,None,None,None,None,None,None
2,1037794,Lois Weber,Hypocrites,1915,movie,54.0,270,4134,32812,0.0089,...,None,None,None,None,None,None,None,None,None,None
3,100036,D.W. Griffith,Judith of Bethulia,1914,movie,61.0,272,4181,32813,0.0087,...,None,None,None,None,None,None,None,None,None,None
4,1307858,Colin Campbell,The Spoilers,1914,movie,110.0,289,4630,32816,0.0101,...,None,None,None,None,None,None,None,None,None,None
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
8078,121003,Nigel Patrick,How to Murder a Rich Uncle,1957,movie,79.0,4292,50527,58211,0.0403,...,None,None,None,None,None,None,None,None,None,None
8079,12345,Virgil W. Vogel,The Land Unknown,1957,movie,78.0,4607,50622,58212,0.0235,...,None,None,None,None,None,None,None,None,None,None
8080,1744,Robert Wise,Until They Sail,1957,movie,94.0,4695,51141,58213,0.0205,...,None,None,None,None,None,None,None,None,None,None
8081,149091,Joseph Anthony,The Matchmaker,1958,movie,103.0,4709,51913,58214,0.0161,...,None,None,None,None,None,None,None,None,None,None
8082,86051,Joshua Logan,South Pacific,1958,movie,157.0,4742,52225,58241,0.0141,...,None,None,None,None,None,None,None,None,None,None

In [11]:
g = pd.read_sql_query("SELECT * FROM vwDirectorStats WHERE cnt > 5;", engine)
g

,person_id,name,cnt,avg_f_per_fr,z_size_mv_mean,z_size_mv_g_mean,z_size_mv_std,z_size_mv_g_std,z_top1_mv_mean,z_top1_mv_g_mean,...,z_v_density_mv_mean,z_v_density_mv_g_mean,z_pct_top1_mv_mean,z_pct_top1_mv_g_mean,z_v_pct_top1_mv_mean,z_v_pct_top1_mv_g_mean,z_pct_face_mv_mean,z_pct_face_mv_g_mean,z_v_pct_face_mv_mean,z_v_pct_face_mv_g_mean
0,1,George Lucas,6,1.597648,-0.041610,0.855329,0.780545,0.770805,-0.177044,0.841838,...,0.0,0.0,0.294330,1.024496,-0.121609,-0.384257,-0.215902,0.694606,-0.216130,0.882069
1,40,Orson Welles,9,1.770517,0.760717,0.147382,0.803468,0.447467,0.946934,0.239790,...,0.0,0.0,0.895747,0.368412,0.136311,0.219619,0.678916,0.170592,1.084606,0.484954
2,68,Fritz Lang,34,1.875934,-0.405865,-0.615508,0.751101,0.368417,-0.423082,-0.668811,...,0.0,0.0,0.425604,-0.085940,0.350757,0.373206,-0.640433,-0.759422,-0.093754,-0.544125
3,138,Quentin Tarantino,7,1.581424,-0.209708,0.904044,0.978506,1.341683,-0.283908,0.882094,...,0.0,0.0,0.123046,1.065475,-0.154927,-0.829141,-0.378659,0.665629,0.339926,1.329571
4,190,Clint Eastwood,33,2.026678,-0.450698,0.319827,0.724653,0.686309,-0.304516,0.590659,...,0.0,0.0,-0.627861,0.342375,0.502038,0.214005,-0.168247,0.650048,-0.417829,0.494872
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
348,940663,Chester M. Franklin,8,1.618405,0.397221,-0.536173,0.979921,0.186557,0.344414,-0.711469,...,0.0,0.0,-0.074203,0.204556,0.396635,0.423442,0.359364,-0.845633,-0.004262,-0.881038
349,1021685,E. Mason Hopper,6,1.722700,-0.272431,-0.511536,0.875585,0.384393,-0.368949,-0.661892,...,0.0,0.0,-0.140713,-0.360212,0.187656,0.395882,-0.543920,-0.749499,-0.404866,-0.776164
350,1036754,Reginald Barker,7,1.812715,0.462617,-0.603244,0.387553,0.377458,0.511501,-0.717664,...,0.0,0.0,-0.135964,-0.093071,0.476419,0.569511,0.635482,-0.748338,0.400587,-0.808398
351,1065336,Melville W. Brown,6,1.830765,-0.720176,-0.767581,0.458246,0.265109,-0.790258,-0.891494,...,0.0,0.0,-0.171937,-0.545736,0.233534,0.283993,-0.921263,-0.962635,-0.877034,-1.083179
352,1225777,Leigh Jason,7,2.091450,0.052269,-0.372497,0.446016,0.175158,0.037722,-0.416537,...,0.0,0.0,-0.571026,-0.908976,-0.168242,0.110692,0.413803,-0.151861,0.094569,-0.405796

In [12]:
# def plot_directors(df, 
#                    x, 
#                    y, 
#                    trendline_options=None, 
#                    hover_data=None, 
#                    xaxis=None, 
#                    yaxis=None, 
#                    dst=None, 
#                    width=800, 
#                    height=600,
#                    layout=None,
#                    plot_title=None,
#                    xaxis_title=None,
#                    yaxis_title=None):
#     if not trendline_options:
#         trendline_options = {}

#     fig = px.scatter(
#         df, 
#         x=x, 
#         y=y, 
#         color_discrete_sequence=["#E100FF"], 
#         hover_data=hover_data,
#         trendline='ols',
#         trendline_options=trendline_options,
#         labels={
#             x: xaxis_title if xaxis_title else x,
#             y: yaxis_title if yaxis_title else y
#         }
#     )
#     if layout:
#         fig.update_layout(layout)
        
#     fig.update_layout(
#         xaxis=dict(title=x if not xaxis else xaxis),
#         yaxis=dict(title=y if not yaxis else yaxis),
#         title=dict(
#             text=plot_title,
#             x=0.5,
#             y=0.95
#         ),
#         width=width,
#         height=height
#     )
#     fig.update_traces(
#     marker=dict(
#         size=10, 
#         line=dict(
#             width=2, 
#             color="white")
#             ),
#     line=dict(
#         dash="dash", 
#         color="#E0E2E5", 
#         width=6),
#     hoverlabel=dict(
#         bgcolor="white",
#         font_size=16,
#         font_color="black"
#         )
#     )
#     fig.update_xaxes(
#         showgrid=True,
#         gridwidth=1,
#         gridcolor="rgba(255, 255, 255, 0.25)"
#     )
#     fig.update_yaxes(
#         showgrid=True,
#         gridwidth=1,
#         gridcolor="rgba(255, 255, 255, 0.25)"
#     )

#     if dst:
#         fig.write_image(dst, width=width, height=height, scale=2)
#     fig.show()

## Analysis

### Face Size

#### Face Size vs. Size Variance

The first measure is relativley simple; it's simply the average size of faces within a film averaged over a director's career. This is plotted against how much the size of the face varies within a film. As we can see, the correlation between these two variables is rather tight.

In [13]:
x = "z_size_mv_g_mean"
y = "z_v_size_mv_g_mean"
plot_directors(g, 
               x, 
               y, 
               xaxis="Avg. Size", 
               yaxis="Std. Size", 
               dst="./plots/avg_size_v_std_size.png",  
               hover_data=["name"], 
               layout=layout,
               width=960,
               height=540,
               plot_title="Avg. Size vs. Std. Size",
               xaxis_title="Avg. Size",
               yaxis_title="Std. Size")

What might be an explanation? Well, the larger the average face size, the more 'dynamic range' the director has available. A director who favors long shots (like Chaplin) is mathematically restricted to a narrow band of variance because the face is already small. A director who favors close-ups (like Bergman) has the 'spatial budget' to swing wildly between different scales. Therefore, shot-size variety is a luxury of the close-up.

#### Face Size vs. Career Volatility

This measures the average scale of the face within a film against a director's tendency to vary that scale *betweeen* films. A high score on the x axis means that the director highly privileges close-ups while a low score means they favor long shots. A high score on the y axis means that a director changes this tendency between films while a low score means that the director remains largely consistent in their shot scales across their career.

In [14]:
x = "z_size_mv_g_mean"
y = "z_size_mv_g_std"
plot_directors(g, 
               x, 
               y, 
               xaxis="Avg. Size",
               yaxis="Size Career Variance",
               dst="./plots/avg_size_v_career_std.png",
               hover_data=["name"],
               layout=layout,
               width=960,
               height=540,
               plot_title="Avg. Size vs. Career Std. Size",
               xaxis_title="Avg. Size",
               yaxis_title="Career Std. Size")

In [15]:
g[['name', 'z_size_mv_g_std']].sort_values('z_size_mv_g_std', ascending=False)[:10].round(2)

                     name  z_size_mv_g_std
57            David Lynch             2.09
62         Ingmar Bergman             2.01
97           Wong Kar-Wai             1.87
10      Christopher Nolan             1.77
47           Sergio Leone             1.48
12           Ridley Scott             1.44
3       Quentin Tarantino             1.34
50   Paul Thomas Anderson             1.26
320      Yorgos Lanthimos             1.23
15            Michael Bay             1.16

In [16]:
g[["name", "z_size_mv_g_std"]].sort_values('z_size_mv_g_std')[:10].round(2)

                 name  z_size_mv_g_std
346     Howard Higgin             0.09
279      John Rawlins             0.11
217   Charles Walters             0.12
69      Buster Keaton             0.13
334   Godfrey Grayson             0.13
176   Fred C. Brannon             0.14
256       Wallace Fox             0.14
319       Ralph Staub             0.15
317  Herbert I. Leeds             0.16
300     Edward Sloman             0.16

#### Face Variance vs. Career Volatility

This plot represents how the variance in face size within a film contrasts with how consistently the face size varies *between* movies.

In [17]:
x = "z_v_size_mv_mean"   # How much do face sizes vary within a movie
y = "z_v_size_mv_g_std"    # How much does a director vary his/her shot scale from one film to the next
plot_directors(g, 
               x, 
               y, 
               xaxis="Std. Size",
               yaxis="Size Career Variance",
               dst="./plots/std_size_v_career_std.png",
               hover_data=["name"],
               layout=layout,
               width=960,
               height=540,
               plot_title="Std. Size vs. Career Std. Size",
               xaxis_title="Std. Size",
               yaxis_title="Career Std. Size")

#### Avg. Size Career Variance vs. Std. Size Career Variance

In [18]:
"""
On the x axis is the STDDEV of average face size. How much does a director vary their face sizes between films. 
If a director always uses the same shot scale across their career--close-ups, for instance--they will have a low value on the x axis.

On the y axis is the STDDEV of face size variance. How much do the face sizes vary within a film, and how much does this change between films.
If a director varies their scales a lot within a movie, how much do they do this across their career.
"""
x = 'z_size_mv_g_std'
y = "z_v_size_mv_g_std"    
plot_directors(g, 
               x, 
               y, 
               xaxis="Career Avg. Size Variance",
               yaxis="Career Std. Size Variance",
               dst="./plots/career_v_avg_vs_career_v_std.png",
               hover_data=["name"],
               layout=layout,
               width=960,
               height=540,
               plot_title="Career Avg. Size Variance vs. Career Std. Size Variance",
               xaxis_title="Career Avg. Size Variance",
               yaxis_title="Career Std. Size Variance")

In [44]:
g[["name", "z_v_size_mv_g_std"]].sort_values(by="z_v_size_mv_g_std")[:10].round(3)

                  name  z_v_size_mv_g_std
319        Ralph Staub              0.127
217    Charles Walters              0.129
310     Bernard B. Ray              0.133
314        Philip Ford              0.137
69       Buster Keaton              0.143
300      Edward Sloman              0.159
260     Elliott Nugent              0.163
345    Marshall Neilan              0.166
232        Jesse Hibbs              0.167
318  Howard Bretherton              0.167

In [45]:
g[["name", "z_v_size_mv_g_std"]].sort_values(by="z_v_size_mv_g_std", ascending=False)[:10].round(3)

                   name  z_v_size_mv_g_std
47         Sergio Leone              1.891
57          David Lynch              1.615
62       Ingmar Bergman              1.578
3     Quentin Tarantino              1.386
320    Yorgos Lanthimos              1.302
97         Wong Kar-Wai              1.299
186  Emeric Pressburger              1.212
96     Vittorio De Sica              1.162
56   Antonio Margheriti              1.131
146       Samuel Fuller              1.095

#### Face Size vs. Avg. Distance

As you can see below, face size and distance to center of the frame are slightly inversely correlated. This makes sense intuitively because the larger a face is, the less room there is to play within the frame.

In [21]:
x = "z_size_mv_g_mean"
y = "z_dist_mv_g_mean"
plot_directors(g, 
               x, 
               y, 
               xaxis="Avg. Size",
               yaxis="Avg. Distance",
               dst="./plots/avg_size_v_avg_distance.png",
               hover_data=["name"],
               layout=layout,
               width=960,
               height=540,
               plot_title="Avg. Size vs. Avg. Distance",
               xaxis_title="Avg. Size",
               yaxis_title="Avg. Distance")

### Density

#### Faces per Frame vs. Face Size

This result was a little surprising to me. Yes, there is an inverse relationship between the number of faces per frame and the size of the face. However, it's weaker than I expected. My guess would be that this is because we're aggregating at the film level instead of the frame level. I imagine if we aggregated by frame we might see a different result.

In [22]:
x = "z_f_per_fr_mv_g_mean"
y = "z_size_mv_g_mean"
plot_directors(g, 
               x, 
               y, 
               xaxis="Avg. Faces per Frame",
               yaxis="Avg. Size",
               dst="./plots/avg_density_vs_avg_size.png",
               hover_data=["name"],
               layout=layout,
               width=960,
               height=540,
               plot_title="Avg. Faces per Frame vs. Avg. Size",
               xaxis_title="Avg. Faces per Frame",
               yaxis_title="Avg. Size")

#### Faces per Frame vs. Avg Distance from Center

There is almost no relationship between faces per frame and the average distance to the center of the frame. I find this surprising since, unless faces are overlaid with each other, more faces should necessitate moving them away from the center. Again, I suspect aggregating at the frame level instead of the film level might result in a stronger relationship.

In [23]:
x = "z_f_per_fr_mv_g_mean"
y = "z_dist_mv_g_mean"
plot_directors(g, 
               x, 
               y, 
               xaxis="Avg. Faces per Frame",
               yaxis="Avg. Distance",
               dst="./plots/avg_density_vs_avg_distance.png",
               hover_data=["name"],
               layout=layout,
               width=960,
               height=540,
               plot_title="Avg. Faces per Frame vs. Avg. Distance",
               xaxis_title="Avg. Faces per Frame",
               yaxis_title="Avg. Distance")

#### Faces per Frame vs. Variance of Distance to Center

In [24]:
x = "z_f_per_fr_mv_g_mean"
y = "z_v_dist_mv_g_mean"
plot_directors(g, 
               x, 
               y, 
               xaxis="Avg. Faces per Frame",
               yaxis="Std. Distance",
               dst="./plots/avg_density_vs_std_distance.png",
               hover_data=["name"],
               layout=layout,
               width=960,
               height=540,
               plot_title="Avg. Faces per Frame vs. Std. Distance",
               xaxis_title="Avg. Faces per Frame",
               yaxis_title="Std. Distance")

#### Faces per Frame vs. Dispersion

In [25]:
x = "z_f_per_fr_mv_g_mean"
y = "z_disp_mv_g_mean"
plot_directors(g, 
               x, 
               y, 
               xaxis="Avg. Faces per Frame",
               yaxis="Dispersion",
               dst="./plots/avg_density_vs_dispersion.png",
               hover_data=["name"],
               layout=layout,
               width=960,
               height=540,
               plot_title="Avg. Faces per Frame vs. Dispersion",
               xaxis_title="Avg. Faces per Frame",
               yaxis_title="Dispersion")

#### Faces per Frame vs. Gini

In [26]:
x = "z_f_per_fr_mv_g_mean"
y = "z_gini_mv_g_mean"
plot_directors(g, 
               x, 
               y, 
               xaxis="Avg. Faces per Frame",
               yaxis="Gini Score",
               dst="./plots/avg_density_vs_gini.png",
               hover_data=["name"],
               layout=layout,
               width=960,
               height=540,
               plot_title="Avg. Faces per Frame vs. Gini Score",
               xaxis_title="Avg. Faces per Frame",
               yaxis_title="Gini Score")

#### Faces per Frame vs. Variance of Faces per Frame

In [27]:
x = "z_f_per_fr_mv_g_mean"
y = "z_v_f_per_fr_mv_g_mean"
plot_directors(g, 
               x, 
               y, 
               xaxis="Avg. Faces per Frame",
               yaxis="Std. Faces per Frame",
               dst="./plots/avg_density_vs_std_density.png",
               hover_data=["name"],
               layout=layout,
               width=960,
               height=540,
               plot_title="Avg. Faces per Frame vs. Std. Faces per Frame",
               xaxis_title="Avg. Faces per Frame",
               yaxis_title="Std. Faces per Frame")

### Distance

#### Distance vs. Variance Distance

In [28]:
x = "z_dist_mv_g_mean"
y = "z_v_dist_mv_g_mean"
plot_directors(g, 
               x, 
               y, 
               xaxis="Avg. Distance",
               yaxis="Std. Distance",
               dst="./plots/avg_distance_vs_std_distance.png",
               hover_data=["name"],
               layout=layout,
               width=960,
               height=540,
               plot_title="Avg. Distance vs. Std. Distance",
               xaxis_title="Avg. Distance",
               yaxis_title="Std. Distance")

#### Distance from Center vs. Gini

In [29]:
x = "z_dist_mv_g_mean"
y = "z_gini_mv_g_mean"
plot_directors(g, 
               x, 
               y, 
               xaxis="Avg. Distance",
               yaxis="Gini Score",
               dst="./plots/avg_distance_vs_gini.png",
               hover_data=["name"],
               layout=layout,
               width=960,
               height=540,
               plot_title="Avg. Distance vs. Gini Score",
               xaxis_title="Avg. Distance",
               yaxis_title="Gini Score")

#### Distance from Center vs. Dispersion

In [30]:
x = "z_dist_mv_g_mean"
y = "z_disp_mv_g_mean"
plot_directors(g, 
               x, 
               y, 
               xaxis="Avg. Distance",
               yaxis="Dispersion",
               dst="./plots/avg_distance_vs_dispersion.png",
               hover_data=["name"],
               layout=layout,
               width=960,
               height=540,
               plot_title="Avg. Distance vs. Dispersion",
               xaxis_title="Avg. Distance",
               yaxis_title="Dispersion")

#### Distance from Center Average vs. Distance from Center Variance

In [31]:
x = "z_dist_mv_g_mean"
y = "z_v_dist_mv_g_mean"
plot_directors(g, 
               x, 
               y, 
               xaxis="Avg. Distance",
               yaxis="Std. Distance",
               dst="./plots/avg_distance_vs_std_distance.png",
               hover_data=["name"],
               layout=layout,
               width=960,
               height=540,
               plot_title="Avg. Distance vs. Std. Distance",
               xaxis_title="Avg. Distance",
               yaxis_title="Std. Distance")

#### Distance from Center Film Variance vs. Distance from Center Career Variance

In [32]:
x = "z_dist_mv_g_std"
y = "z_v_dist_mv_g_std"
plot_directors(g, 
               x, 
               y, 
               xaxis="Career Avg. Distance",
               yaxis="Career Std. Distance",
               dst="./plots/career_avg_distance_vs_career_std_distance.png",
               hover_data=["name"],
               layout=layout,
               width=960,
               height=540,
               plot_title="Career Avg. Distance vs. Career Std. Distance",
               xaxis_title="Career Avg. Distance",
               yaxis_title="Career Std. Distance")

#### Distance from Center Variance vs. Gini

In [33]:
x = "z_v_dist_mv_g_mean"
y = "z_gini_mv_g_mean"
plot_directors(g, 
               x, 
               y, 
               xaxis="Std. Distance",
               yaxis="Gini Score",
               dst="./plots/std_distance_vs_gini.png",
               hover_data=["name"],
               layout=layout,
               width=960,
               height=540,
               plot_title="Std. Distance vs. Gini Score",
               xaxis_title="Std. Distance",
               yaxis_title="Gini Score")

#### Distance from Center Variance vs. Dispersion

In [34]:
x = "z_v_dist_mv_g_mean"
y = "z_disp_mv_g_mean"
plot_directors(g, 
               x, 
               y, 
               xaxis="Std. Distance",
               yaxis="Dispersion",
               dst="./plots/std_distance_vs_dispersion.png",
               hover_data=["name"],
               layout=layout,
               width=960,
               height=540,
               plot_title="Std. Distance vs. Dispersion",
               xaxis_title="Std. Distance",
               yaxis_title="Dispersion")

#### Distance from Center Variance vs. Vertical Discipline

In [35]:
x = "z_v_dist_mv_g_mean"
y = "z_vert_mv_g_mean"
plot_directors(g, 
               x, 
               y, 
               xaxis="Std. Distance",
               yaxis="Vertical Discipline",
               dst="./plots/std_distance_vs_v_discipline.png",
               hover_data=["name"],
               layout=layout,
               width=960,
               height=540,
               plot_title="Std. Distance vs. Vertical Discipline",
               xaxis_title="Std. Distance",
               yaxis_title="Vertical Discipline")

#### Distance to Center vs. Horizontal Spread

In [36]:
x = "z_v_dist_mv_g_mean"
y = "z_h_spread_mv_g_mean"
plot_directors(g, 
               x, 
               y, 
               xaxis="Std. Distance",
               yaxis="Horizontal Spread",
               dst="./plots/std_distance_vs_h_spread.png",
               hover_data=["name"],
               layout=layout,
               width=960,
               height=540,
               plot_title="Std. Distance vs. Horizontal Spread",
               xaxis_title="Std. Distance",
               yaxis_title="Horizontal Spread")

### Vertical Discipline

#### Vertical Discipline vs. Dispersion

In [37]:
x = "z_vert_mv_g_mean"
y = "z_disp_mv_g_mean"
plot_directors(g, 
               x, 
               y, 
               xaxis="Vertical Discipline",
               yaxis="Dispersion",
               dst="./plots/v_disc_vs_dispersion.png",
               hover_data=["name"],
               layout=layout,
               width=960,
               height=540,
               plot_title="Vertical Discipline vs. Dispersion",
               xaxis_title="Vertical Discipline",
               yaxis_title="Dispersion")

#### Vertical Discipline vs. Gini

In [38]:
x = "z_vert_mv_g_mean"
y = "z_gini_mv_g_mean"
plot_directors(g, 
               x, 
               y, 
               xaxis="Vertical Discipline",
               yaxis="Gini Score",
               dst="./plots/v_disc_vs_gini.png",
               hover_data=["name"],
               layout=layout,
               width=960,
               height=540,
               plot_title="Vertical Discipline vs. Gini Score",
               xaxis_title="Vertical Discipline",
               yaxis_title="Gini Score")

#### Vertical Discipline vs. Horizontal Spread

In [39]:
x = "z_vert_mv_g_mean"
y = "z_h_spread_mv_g_mean"
plot_directors(g, 
               x, 
               y, 
               xaxis="Vertical Discipline",
               yaxis="Horizontal Spread",
               dst="./plots/v_disc_vs_h_spread.png",
               hover_data=["name"],
               layout=layout,
               width=960,
               height=540,
               plot_title="Vertical Discipline vs. Horizontal Spread",
               xaxis_title="Vertical Discipline",
               yaxis_title="Horizontal Spread")

### Gini

#### Gini vs. Dispersion

In [40]:
x = "z_gini_mv_g_mean"
y = "z_disp_mv_g_mean"
plot_directors(g, 
               x, 
               y, 
               xaxis="Gini Score",
               yaxis="Dispersion",
               dst="./plots/gini_vs_dispersion.png",
               hover_data=["name"],
               layout=layout,
               width=960,
               height=540,
               plot_title="Gini Score vs. Dispersion",
               xaxis_title="Gini Score",
               yaxis_title="Dispersion")

In [41]:
g[["name", "z_disp_mv_g_mean"]].sort_values("z_disp_mv_g_mean")[:10]

                 name  z_disp_mv_g_mean
276      Yasujirō Ozu         -1.454087
69      Buster Keaton         -1.204122
328  Denis Villeneuve         -1.169020
176   Fred C. Brannon         -1.158047
106     Alan Crosland         -1.111063
172        Ray Taylor         -1.102520
213      Rian Johnson         -1.092279
193   Sidney Franklin         -1.072942
201       E.A. Dupont         -1.067818
21         Ethan Coen         -1.028674

In [42]:
g[["name", "z_disp_g_mean"]].sort_values("z_disp_g_mean", ascending=False)[:10]

KeyError: "['z_disp_g_mean'] not in index"

#### Gini vs. Horizontal Spread

In [ ]:
x = "z_gini_mv_g_mean"
y = "z_h_spread_mv_g_mean"
plot_directors(g, 
               x, 
               y, 
               xaxis="Gini Score",
               yaxis="Horizontal Spread",
               dst="./plots/gini_vs_h_spread.png",
               hover_data=["name"],
               layout=layout,
               width=960,
               height=540,
               plot_title="Gini Score vs. Horizontal Spread",
               xaxis_title="Gini Score",
               yaxis_title="Horizontal Spread")